version: '3'

services:
  kafka-rest:
    container_name: kafka-rest
    image: mauricioromagnollo/kafka-rest:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_HOST=kafka:29092

  # kafka-rest-test:
  #   container_name: kafka-rest-test
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - .:/app