version: '3'

services:
  kafrest:
    container_name: kafrest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}
    networks:
      - kafrest

  kafrest-latest:
    container_name: kafrest-latest
    image: mauricioromagnollo/kafrest:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}
    networks:
      - kafrest

networks:
  kafrest:
    driver: bridge