version: '3'

services:
  kafrest:
    container_name: kafrest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}
    networks:
      - kafrest

  kafrest-latest:
    container_name: kafrest-latest
    image: mauricioromagnollo/kafrest:latest
    ports:
      - "8888:8080"
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}
    networks:
      - kafrest

  mkdocs:
    container_name: kafrest-mkdocs
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    image: kafrest-mkdocs-image
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - kafrest

networks:
  kafrest:
    driver: bridge