name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
    paths:
      - "cmd/**"
      - "external/**"
      - "internal/**"
      - Dockerfile
      - .github/workflows/publish.yml

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t mauricioromagnollo/kafrest:latest .

      - name: Login to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Publish Docker Image to Docker Hub
        if: success()
        run: |
          docker push mauricioromagnollo/kafrest
